### ISSUE TITLE
Make a wiki for API part of kagstats

### ISSUE THREAD

**Issue by moonburnt** [Harrison-Miller/kagstats#16]
It could be nice to have a wiki containing list of valid calls to kagstats api and their description. Coz opening [related go script](https://github.com/Harrison-Miller/kagstats/blob/master/api/api.go) and manually checking the results for each r.HandleFunc isnt that intuitive. I mean - Im still having hard time finding if there is a call to get info regarding total player's kills amount, favorite weapon and such (coz '/players/{id:[0-9]+}/kills' seem to only return player's recent kills feed)

**Comment by Harrison-Miller** [comment]
Yes that would be nice. The best way to figure out how to use the API is to open the developer console and explore the website. It'll be much more effective than reading the source code.

**Comment by Harrison-Miller** [comment]
for total kills just go to https://kagstats.com/api/players/53/basic.

**Comment by Harrison-Miller** [comment]
swagger docs will be added in the next release probably tomorrow
