### ISSUE TITLE
Inconsistency between empty responses

### ISSUE THREAD

**Issue by moonburnt** [Harrison-Miller/kagstats#20]
I dont know if this is a bug, but requesting invalid user's info from [players/{id}/basic](https://github.com/Harrison-Miller/kagstats/blob/master/api/basicstats.go#L40) and [/players/lookup/{name:.+}](https://github.com/Harrison-Miller/kagstats/blob/master/api/basicstats.go#L41) return different http response codes - one gives 404, other 500 (and sql-related error message).

If such inconsistency is intended feature - just close this issue

**Comment by moonburnt** [comment]
another example of similar problem is requesting info about nemesis/bullied users from player who dont have these. Having no nemesis returns sql error, having no bullied players - {"bullied": null}.
Example (as for the moment of writing): 
https://kagstats.com/api/players/13450/nemesis
https://kagstats.com/api/players/13450/bullied

**Comment by Harrison-Miller** [comment]
will look into improving the consistency soon.

**Comment by Harrison-Miller** [comment]
@moonburnt can you actually send me an example of it failing for /basic and lookup.

**Comment by Harrison-Miller** [comment]
from what I just tested with players/{id} players/{id}/basic /players/lookup/{name} all 3 return a 500 if there is an issue a 404 would only happen if you went to an endpoint that didn't exist.

The only other error code that would be returned by the API would be Bad Request which is 400.

**Comment by Harrison-Miller** [comment]
Closing - API no longer returns SQL errors (dangerous).
/bullied will return [] if nothing is found
/nemesis will return 0 for deaths null for nemesis
/hitters will return [] if nothing is found
/basic will return 0 for all stats if nothing is found
