### ISSUE TITLE
human-readable list of hitters

### ISSUE THREAD

**Issue by moonburnt** [Harrison-Miller/kagstats#21]
If Im correct, hitters refer to most popular weaponry used by player. But doing `https://kagstats.com/api/players/{player_id}/hitters` returns just bunch of internal ids instead of keys. Is there a human-readable list of these? I can guess some by looking up to people's profiles, but there are still lot of unknown entries to find out manually

**Comment by Harrison-Miller** [comment]
the hitter ids get set from the game side when sent to the collector which comes from this file: https://github.com/transhumandesign/kag-base/blob/master/Entities/Common/Attacks/Hitters.as

Then in the UI I just have the same info back again. https://github.com/Harrison-Miller/kagstats/blob/master/ui/src/app/hitters.ts#L68

**Comment by Harrison-Miller** [comment]
will work on adding this to the api for hitters for external users.

**Comment by Harrison-Miller** [comment]
Closing - the api no returns the hitter name as well as id.
